/**
 * IATA -> Spanish city name for user-facing posts. Falls back to the
 * raw IATA code for anything unmapped, so adding routes never breaks
 * publishing.
 */

const CITY_BY_IATA: Record<string, string> = {
	// Origins
	EZE: "Buenos Aires",
	AEP: "Buenos Aires",
	COR: "Córdoba",
	MDZ: "Mendoza",
	ROS: "Rosario",
	// Regional
	GRU: "San Pablo",
	GIG: "Río de Janeiro",
	FLN: "Florianópolis",
	SSA: "Salvador de Bahía",
	REC: "Recife",
	BSB: "Brasilia",
	CNF: "Belo Horizonte",
	POA: "Porto Alegre",
	CWB: "Curitiba",
	FOR: "Fortaleza",
	IGU: "Foz de Iguazú",
	SCL: "Santiago de Chile",
	MVD: "Montevideo",
	PDP: "Punta del Este",
	ASU: "Asunción",
	LIM: "Lima",
	CUZ: "Cusco",
	VVI: "Santa Cruz de la Sierra",
	LPB: "La Paz",
	BOG: "Bogotá",
	MDE: "Medellín",
	CTG: "Cartagena",
	UIO: "Quito",
	GYE: "Guayaquil",
	// Caribbean
	CUN: "Cancún",
	PUJ: "Punta Cana",
	SDQ: "Santo Domingo",
	HAV: "La Habana",
	VRA: "Varadero",
	SJU: "San Juan",
	AUA: "Aruba",
	CUR: "Curazao",
	MBJ: "Montego Bay",
	NAS: "Nassau",
	// USA
	MIA: "Miami",
	FLL: "Fort Lauderdale",
	MCO: "Orlando",
	TPA: "Tampa",
	JFK: "Nueva York",
	EWR: "Nueva York",
	BOS: "Boston",
	IAD: "Washington",
	ATL: "Atlanta",
	ORD: "Chicago",
	DFW: "Dallas",
	IAH: "Houston",
	DEN: "Denver",
	LAS: "Las Vegas",
	LAX: "Los Ángeles",
	SFO: "San Francisco",
	SEA: "Seattle",
	CLT: "Charlotte",
	// Europe
	MAD: "Madrid",
	BCN: "Barcelona",
	AGP: "Málaga",
	PMI: "Palma de Mallorca",
	VLC: "Valencia",
	LIS: "Lisboa",
	OPO: "Oporto",
	FCO: "Roma",
	MXP: "Milán",
	VCE: "Venecia",
	NAP: "Nápoles",
	CDG: "París",
	ORY: "París",
	NCE: "Niza",
	AMS: "Ámsterdam",
	LHR: "Londres",
	LGW: "Londres",
	FRA: "Fráncfort",
	MUC: "Múnich",
	BER: "Berlín",
	ZRH: "Zúrich",
	VIE: "Viena",
	BRU: "Bruselas",
	DUB: "Dublín",
	CPH: "Copenhague",
	ATH: "Atenas",
	IST: "Estambul",
	// Other
	TLV: "Tel Aviv",
	AKL: "Auckland",
	SYD: "Sídney",
	DOH: "Doha",
	DXB: "Dubái",
	JNB: "Johannesburgo",
	NRT: "Tokio",
	ICN: "Seúl",
	PVG: "Shanghái",
	HKG: "Hong Kong",
	BKK: "Bangkok",
	SIN: "Singapur",
	DEL: "Nueva Delhi",
	CAI: "El Cairo",
	MEX: "Ciudad de México",
	SJO: "San José de Costa Rica",
	PTY: "Ciudad de Panamá",
};

export function cityName(iata: string): string {
	return CITY_BY_IATA[iata] ?? iata;
}
